### ISSUE TITLE
validation tests: make the time constraints more generous

### ISSUE THREAD

**Issue by TomasTomecek** [packit/validation#15]
Last two days, two validation checks failed even though all GitHub check runs were green after some time:

https://github.com/packit/hello-world/runs/6587387284
https://sentry.io/share/issue/3d1ddfb488cd40eaae3550af18f15d00/
https://sentry.io/organizations/red-hat-0p/issues/3297006723/?referrer=alert_email&alert_type=email&alert_timestamp=1653371582691&alert_rule_id=855946&environment=production

Let's make the time limits more generous and aligned with our actual OKRs.

Example: check `Basic test case: copr build and test (https://github.com/packit/hello-world/pull/648) failed: These check runs were not completed 20 minutes` is too strict.

**Comment by mfocko** [comment]
### Update on the issue

Currently we we're at 30 minutes… I see some failures in the Sentry, but it appears they are caused by the fact we have some deprecated targets in the PRs that we reuse (apparently got into pending sometime around branching and got stuck…) :/

**Comment by mfocko** [comment]
Based on the discussion on the architecture (a week ago), we agreed on keeping the current timeout and changing it further, if required. Therefore closing this issue as done, since the timeout has already changed from the reporting.
